export const FETCHING_BOARDS = 'FETCHING_BOARDS';
export const BOARDS_FETCHED_SUCCESSFULLY = 'BOARDS_FETCHED_SUCCESSFULLY';
export const FETCHING_BOARD = 'FETCHING_BOARD';
export const BOARD_FETCHED_SUCCESSFULLY = 'BOARD_FETCHED_SUCCESSFULLY';
export const UPDATING_LIST = 'UPDATING_LIST';
export const LIST_UPDATED_SUCCESSFULLY = 'LIST_UPDATED_SUCCESSFULLY';
